project_id = "thnusgshpnktmphivphf"

[functions.partner-auth]
verify_jwt = false

[functions.api-generate-key]
verify_jwt = true

[functions.vault-search]
verify_jwt = false

[functions.openplay-webhook]
verify_jwt = false

[functions.cowriter-agent]
verify_jwt = false

[functions.training-upload]
verify_jwt = true